<?php
return[
    "Gestión de inventario para abastecimiento de piezas",
    "Web de animación sociocultural",
    "Plataforma de aprendizaje en línea",
    "Sistema de reservas para hoteles",
    "Portal de noticias locales",
    "Tienda en línea de productos artesanales",
    "Sistema de gestión de pacientes para clínicas",
    "Aplicación de seguimiento de hábitos personales",
    "Plataforma de comercio electrónico B2B",
    "Web para reserva de eventos y espectáculos",
    "Sistema de gestión financiera para PYMEs",
    "Plataforma de tutorías en línea",
    "Portal de empleo y reclutamiento",
    "Sistema de gestión de bibliotecas",
    "Aplicación para el monitoreo de condiciones climáticas",
    "Portal educativo para estudiantes de secundaria",
    "Plataforma de crowdfunding",
    "Aplicación de entrega de alimentos a domicilio",
    "Sistema de votación en línea",
    "Web de consulta médica remota",
    "Portal de viajes y turismo",
    "Aplicación para el seguimiento de pedidos en tiempo real",
    "Plataforma de gestión de proyectos",
    "Web de cursos de idiomas en línea",
    "Sistema de control de acceso y seguridad",
    "Plataforma de venta de entradas para conciertos",
    "Aplicación de gestión de eventos deportivos",
    "Portal de asesoría legal en línea",
    "Sistema de reportes ambientales",
    "Aplicación de servicios de limpieza a domicilio",
    "Web de asesoramiento financiero",
    "Plataforma para artistas y galerías",
    "Sistema de seguimiento de flotas vehiculares",
    "Portal de bienestar y salud mental",
    "Aplicación de gestión de alquileres inmobiliarios",
    "Plataforma de formación para empleados",
    "Web de fotografía y portfolios",
    "Sistema de encuestas y opiniones",
    "Aplicación para la planificación de bodas",
    "Portal de trucos y consejos de bricolaje",
    "Sistema de administración escolar",
    "Web de recetas y cocina",
    "Plataforma de gestión de contenidos multimedia",
    "Sistema de reservas para spas y salones de belleza",
    "Aplicación de seguimiento de inventario de tiendas",
    "Portal de entrenamiento fitness en línea",
    "Sistema de citas para consultorios odontológicos",
    "Aplicación de control parental",
    "Plataforma de análisis y datos de mercado",
    "Sistema de gestión de recursos humanos",
    "Web para la difusión de eventos culturales",
];
